name: csbrl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: microsoft/setup-msbuild@v1.1

      - name: build
        run: msbuild numpadEmu.sln /p:Configuration=Release

      - name: list
        run: dir ${{ github.workspace }}\x64\Release

      - name: release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: |
            D:\a\numpad-layout-switch\numpad-layout-switch\x64\Release\numpadEmu.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
