name: build & release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Solution
      shell: cmd
      run: |
        if exist numpadEmu.sln (
          msbuild numpadEmu.sln /p:Configuration=Release /p:Platform=x64
        ) else (
          cl numpadEmu.cpp /Fe:numpadEmu.exe /O2 /EHsc
        )

    - name: Verify executable exists
      id: verify_exe
      shell: cmd
      run: |
        if exist x64/Release/numpadEmu.exe (
          echo "exe_exists=true" >> $GITHUB_OUTPUT
        ) else (
          echo "exe_exists=false" >> $GITHUB_OUTPUT
        )

    - name: Upload Artifact
      if: steps.verify_exe.outputs.exe_exists == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: numpadEmu
        path: numpadEmu.exe

  release:
    needs: build
    if: needs.build.steps.verify_exe.outputs.exe_exists == 'true'
    runs-on: windows-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: numpadEmu

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: numpadEmu.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
