name: csbr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: microsoft/setup-msbuild@v1.1

      - name: build
        run: msbuild numpadEmu.sln /p:Configuration=Release

      - name: Find Executable
        id: find_executable
        run: |
          echo "searching the exe..."
          exe_path=$(find ${{ github.workspace }} -name "numpadEmu.exe" -print -quit)
          echo "found at: $exe_path"
          echo "::set-output name=exe_path::$exe_path"

      - name: release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: ${{ steps.find_executable.outputs.exe_path }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
